server:
  port: 8091

spring:
  mail:
    host: smtp.gmail.com
    username: shams.tabrez11@gmail.com
    password: kxyupevevtddcbgz
    fromAddress: shamst242@gmail.com
    createUserSubject: Your account is created, change the password
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
